default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: r4mik
  timeout: 5000
  reaping_frequency: 30
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_rails_pg_development
  password: <%= Rails.application.credentials.dig(:database, :password) %>

test:
  <<: *default
  database: api_rails_pg_test
  password: <%= Rails.application.credentials.dig(:database, :password) %>

production:
  <<: *default
  database: api_rails_pg_production
  password: <%= ENV["EXERCISE_DATABASE_PASSWORD"] %>

